/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordlenth;

import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    System.out.println(" give word:");
    Scanner SCN = new Scanner(System.in);

    String w = SCN.nextLine();
    
    System.out.println();
    for (int i = 0; i < w.length(); i++) {
      System.out.println(w);
    }

    SCN.close();

  }
}
