/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dotleader;

import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    Scanner SCN =  new Scanner(System.in);
    
    System.out.println("First Word Please:");
    String in1 = SCN.nextLine();
    System.out.println("Second Word Please:");
    String in2 = SCN.nextLine();

    System.out.print(in1);
    for(int i=0; i < 30-in1.length()-in2.length(); i++){
      System.out.print(".");
    }
    System.out.println(in2);
  }
}
